List<Map<String, dynamic>> gadgets = [
  {
    'category': 'Smartphone',
    'description':
        'A flagship smartphone with excellent camera and performance.',
    'itemId': '1',
    'name': 'SuperPhone X',
    'discountPrice': 899.99,
    'price': 999.99,
    'likes': 15000,
    'reviews': 3000,
    'specs': ['8GB', '256GB', '50MP'],
    'favorites': 12000,
    'rates': 4.8,
    'imagePath': 'assets/images/iphone.png',
  },
  {
    'category': 'Laptop',
    'description':
        'Lightweight laptop with powerful performance and battery life.',
    'itemId': '2',
    'name': 'UltraBook Pro',
    'discountPrice': 1199.99,
    'price': 1399.99,
    'likes': 9000,
    'reviews': 1200,
    'specs': ['16GB RAM', '512GB SSD', 'Intel i7 Processor'],
    'favorites': 8000,
    'rates': 4.6,
    'imagePath': 'assets/images/macbook.png',
  },
  {
    'category': 'Tablet',
    'description': 'A sleek tablet for productivity and entertainment.',
    'itemId': '3',
    'name': 'TabMaster 10',
    'discountPrice': 499.99,
    'price': 549.99,
    'likes': 7000,
    'reviews': 850,
    'specs': ['10-inch Display', '4GB RAM', '128GB Storage'],
    'favorites': 6500,
    'rates': 4.5,
    'imagePath': 'assets/images/macbook.png',
  },
  {
    'category': 'Controller',
    'description': 'Stylish ctroller with good and slippery-free casing.',
    'itemId': '4',
    'name': 'Wireless controller',
    'discountPrice': 249.99,
    'price': 299.99,
    'likes': 12000,
    'reviews': 2200,
    'specs': ['GPS', '7-Day Battery Life'],
    'favorites': 10000,
    'rates': 4.7,
    'imagePath': 'assets/images/x-console.png',
  },
  {
    'category': 'Headphones',
    'description': 'Wireless headphones with noise cancellation and deep bass.',
    'itemId': '5',
    'name': 'BassBeat 500',
    'discountPrice': 199.99,
    'price': 249.99,
    'likes': 11000,
    'reviews': 1800,
    'specs': ['Bluetooth 5.0', '30 Hours Battery Life', 'ANC'],
    'favorites': 9500,
    'rates': 4.4,
    'imagePath': 'assets/images/ep1.png',
  },
  {
    'category': 'Camera',
    'description':
        'Compact digital camera with high resolution and video capabilities.',
    'itemId': '6',
    'name': 'PixelShot Pro',
    'discountPrice': 599.99,
    'price': 699.99,
    'likes': 6000,
    'reviews': 1000,
    'specs': ['24MP', '4K Video', 'Optical Zoom'],
    'favorites': 5200,
    'rates': 4.3,
    'imagePath': 'assets/images/ep1.png',
  },
  {
    'category': 'Gaming Console',
    'description':
        'Next-gen gaming console with stunning graphics and performance.',
    'itemId': '7',
    'name': 'GameBox One',
    'discountPrice': 499.99,
    'price': 549.99,
    'likes': 14000,
    'reviews': 3000,
    'specs': ['4K HDR', '1TB Storage', 'Online Multiplayer'],
    'favorites': 12500,
    'rates': 4.9,
    'imagePath': 'assets/images/xbox.png',
  },
  // {
  //   'category': 'Smart Speaker',
  //   'description':
  //       'Smart speaker with voice assistant and superior sound quality.',
  //   'itemId': '8',
  //   'name': 'EchoSound Max',
  //   'discountPrice': 149.99,
  //   'price': 199.99,
  //   'likes': 8000,
  //   'reviews': 950,
  //   'specs': '360° Sound, Voice Commands, WiFi',
  //   'favorites': 7200,
  //   'rates': 4.6,
  //   'imagePath': 'assets/images/echosound_max.png',
  // },
  // {
  //   'category': 'Drone',
  //   'description': 'High-performance drone with 4K video and GPS control.',
  //   'itemId': '9',
  //   'name': 'SkyFlyer Pro',
  //   'discountPrice': 899.99,
  //   'price': 999.99,
  //   'likes': 5000,
  //   'reviews': 700,
  //   'specs': '4K Camera, 30 Min Flight Time, GPS',
  //   'favorites': 4500,
  //   'rates': 4.5,
  //   'imagePath': 'assets/images/skyflyer_pro.png',
  // },
  // {
  //   'category': 'VR Headset',
  //   'description':
  //       'Immersive virtual reality headset for gaming and experiences.',
  //   'itemId': '10',
  //   'name': 'VisionVR X',
  //   'discountPrice': 349.99,
  //   'price': 399.99,
  //   'likes': 10000,
  //   'reviews': 1500,
  //   'specs': '1080p Display, Motion Tracking, Wireless',
  //   'favorites': 8500,
  //   'rates': 4.8,
  //   'imagePath': 'assets/images/visionvr_x.png',
  // },
];
